# -*- coding: utf-8 -*-
"""restaurant sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMK7K2T7Kk_NRjgSJ7mjQGYwPuUMzlg4
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

restaurants_sales_data=pd.read_csv('Restaurant sales.csv')
print(restaurants_sales_data .head())

restaurants_sales_data.shape

restaurants_sales_data.info()

restaurants_sales_data.describe()

restaurants_sales_data.isnull().sum()

restaurants_sales_data["item_name"]=restaurants_sales_data["item_name"].fillna(restaurants_sales_data["item_name"].mode()[0])
restaurants_sales_data

restaurants_sales_data["item_type"].str.upper()

restaurants_sales_data.duplicated().sum()

restaurants_sales_data["transaction_type"].value_counts()

restaurants_sales_data.groupby("item_name")["quantity"].sum()

unique_item_name=restaurants_sales_data["item_name"].unique()
print("unique item name:")
for item_name in unique_item_name:
  print(item_name)

total_quantity_sold=restaurants_sales_data["quantity"].sum()
print(f'total quantity of goods sold:{total_quantity_sold}')

total_quantity_sold_by_item=restaurants_sales_data.groupby("item_name")["quantity"].sum()
print("total quantity of goods sold for each item:")
print(total_quantity_sold_by_item)

"""Data Visualization


1.  Line Plot


"""

daily_sales=restaurants_sales_data.groupby('time_of_sale')['transaction_amount'].sum()
daily_sales.head()

plt.plot(daily_sales.index,daily_sales.values)
plt.xticks(rotation=45)
plt.show()

time_of_day_sales=restaurants_sales_data.groupby('time_of_sale')['transaction_amount'].sum()
time_of_day_sales

plt.bar(time_of_day_sales.index,time_of_day_sales.values)
plt.xlabel('time_of_sale')
plt.ylabel('transaction_amount')
plt.show()

plt.scatter(restaurants_sales_data['item_name'],restaurants_sales_data['item_price'])
plt.xlabel('item_name')
plt.xticks(rotation=45)
plt.ylabel('item_price')
plt.show()

"""Seaborn line plot"""

sns.set_theme(style="darkgrid")

sns.lineplot(x='quantity',y='transaction_amount', hue='item_type',data=restaurants_sales_data,marker='o')
plt.title('item of sales')
plt.figsize=(10,6)
plt.xticks(rotation=45)
plt.show()

sns.barplot(x='time_of_sale',y='transaction_amount',hue='item_type',data=restaurants_sales_data)
plt.title('item of sales')
plt.show()

sns.histplot(restaurants_sales_data['transaction_amount'],bins=20)
plt.show()

sns.scatterplot(x='item_name',y='item_price',data=restaurants_sales_data)
plt.xticks(rotation=45)
plt.show()

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

X = restaurants_sales_data.drop(columns=["transaction_amount", "order_id", "date"])
y = restaurants_sales_data["transaction_amount"]

cat_cols = X.select_dtypes(include="object").columns
num_cols = X.select_dtypes(exclude="object").columns

preprocess = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ("num", "passthrough", num_cols)
])

model = RandomForestRegressor(random_state=42)

pipe = Pipeline([
    ("preprocess", preprocess),
    ("model", model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)

# Import evaluation metrics
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

# Predict on test data
y_pred = pipe.predict(X_test)

# Calculate RMSE
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("Root Mean Square Error (RMSE):", rmse)

# Calculate R2 Score
r2 = r2_score(y_test, y_pred)
print("R2 Score:", r2)

!pip install gradio scikit-learn pandas joblib numpy

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestRegressor
import joblib

# Load dataset
df = pd.read_csv("Restaurant sales.csv")

# Features & target
X = df.drop(columns=["transaction_amount", "order_id", "date"])
y = df["transaction_amount"]

cat_cols = X.select_dtypes(include="object").columns
num_cols = X.select_dtypes(exclude="object").columns

preprocess = ColumnTransformer([
    ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
    ("num", "passthrough", num_cols)
])

model = RandomForestRegressor(random_state=42)

pipe = Pipeline([
    ("preprocess", preprocess),
    ("model", model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipe.fit(X_train, y_train)

# Save model
joblib.dump(pipe, "model.pkl")

print("Model saved successfully")

import gradio as gr
import pandas as pd
import joblib

# Load trained model
model = joblib.load("model.pkl")

# Prediction function
def predict_sales(item_name, item_type, item_price, quantity,
                  transaction_type, received_by, time_of_sale):

    input_data = pd.DataFrame([{
        "item_name": item_name,
        "item_type": item_type,
        "item_price": item_price,
        "quantity": quantity,
        "transaction_type": transaction_type,
        "received_by": received_by,
        "time_of_sale": time_of_sale
    }])

    prediction = model.predict(input_data)
    return f"Predicted Transaction Amount: ₹ {round(prediction[0], 2)}"

# Gradio Interface
interface = gr.Interface(
    fn=predict_sales,
    inputs=[
        gr.Dropdown(["Vadapav", "Aalopuri", "Sugarcane juice"], label="Item Name"),
        gr.Dropdown(["Fastfood", "Beverages"], label="Item Type"),
        gr.Number(label="Item Price"),
        gr.Number(label="Quantity"),
        gr.Dropdown(["Cash", "Online"], label="Transaction Type"),
        gr.Dropdown(["Mr.", "Mrs."], label="Received By"),
        gr.Dropdown(["Morning", "Afternoon", "Evening", "Night"], label="Time of Sale")
    ],
    outputs="text",
    title="🍽️ Restaurant Sales Prediction",
    description="Predict restaurant transaction amount using Machine Learning"
)

interface.launch(share=True)